import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { createHmac } from 'crypto'

const adminSupabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
)

/**
 * Minimal HS256 JWT verification using Node built-in crypto.
 * Tokens are generated by the beta email script using the same secret.
 */
function verifyBetaToken(token: string, secret: string): { user_id: string; exp: number } {
  const parts = token.split('.')
  if (parts.length !== 3) throw new Error('Invalid token format')

  const [headerB64, payloadB64, signatureB64] = parts
  const expectedSig = createHmac('sha256', secret)
    .update(`${headerB64}.${payloadB64}`)
    .digest('base64url')

  if (expectedSig !== signatureB64) throw new Error('Invalid signature')

  const payload = JSON.parse(Buffer.from(payloadB64, 'base64url').toString('utf8'))
  if (payload.exp && payload.exp < Math.floor(Date.now() / 1000)) {
    throw new Error('Token expired')
  }
  if (!payload.user_id) throw new Error('Missing user_id')
  return payload
}

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url)
  const token = searchParams.get('token')

  if (!token) {
    return NextResponse.redirect(new URL('/dashboard?beta=invalid', req.url))
  }

  try {
    const secret = process.env.SUPABASE_JWT_SECRET ?? ''
    const { user_id: userId } = verifyBetaToken(token, secret)

    const { error } = await adminSupabase
      .from('user_profiles')
      .update({
        tier_expiry: '2026-04-30T03:00:00Z',
        beta_extension_claimed: true,
      })
      .eq('id', userId)
      .eq('beta_extension_claimed', false)  // idempotent

    if (error) throw error

    return NextResponse.redirect(new URL('/dashboard?beta=extended', req.url))
  } catch (err) {
    console.error('beta confirm-extension error', err)
    return NextResponse.redirect(new URL('/dashboard?beta=invalid', req.url))
  }
}
